### ISSUE TITLE
Step 5: 📋 Create a Project Backlog

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v39-toucans-team-03#6]
From voyage-template created by [jdmedlock](https://github.com/jdmedlock): chingu-voyages/voyage-template#9  

**__Task Description__**
- [x] Watch the [How to Create a Project Backlog](https://youtu.be/FaoT-DTtXyA) video
[![video link](https://img.youtube.com/vi/Hdn1V645Rwk/0.jpg)](https://youtu.be/FaoT-DTtXyA)
- [x] Identify & prioritize features
- [x] Create an epic for each feature
- [ ] Choose the highest priority epics & divide them into user stories
- [ ] Add your epics & user stories to a backlog tool. Due to it’s tight integration with GitHub we suggest using ZenHub (it’s free for teams using public repositories)
- [ ] Prioritize the user stories

**__Technical Considerations__**
N/a

**__Additional Considerations__**
During the Voyage you’ll refine the Project Backlog and in every Sprint you’ll move tasks from it to the Sprint Backlog. This is part of the Agile process helps you and your team concentrate only on the tasks that must be completed in that Sprint.

If you are using ZenHub don't forget you'll need to install its [browser extension](https://www.zenhub.com/extension) before you can see the ZenHub tab in your GitHub repo.

**__Resources__**
[Create a Project Backlog (Chingu Handbook)](https://www.notion.so/Voyages-8d8e16a5f86e42a88d9ace16bc555f18#5e31d01bed374d019e061c0242ab1f28)

**Member of Epic:** #16

**Comment by Hmmm-mm** [comment]
- Epic : To know which question user is through
  - Set a progress bar below to show how much user makes
- Epic : To get to know the questions well & page looks more fluent
  - Put pictures related to questions next to them
- Epic : Giving an entertainment to Users
  - Give a motion when clicking options
  - Put Jeff Bezos picture when loading the result like an easter egg
- Epic : Giving an interacting features to users
  - Make checkable list in the result page
  - Progress bar for checklist
- Epic : To share the results and get more users to enjoy
  - Add buttons to share the result through messenger apps
  - Always end sentences on a positive note.

**Comment by Hmmm-mm** [comment]
- Comparing Backlog tools (Trello vs. Zenhub)
  - [Zenhub](https://app.zenhub.com/workspaces/lostfound-625fd7e969996e001692d5e1/roadmap)
  - [Trello](https://trello.com/b/9kIRUkVs/kanban-template)
- Let me know your email address & tell your opinion which one you want to use.
- If you are wonder my opinion, I would like to use Zenhub
  - It is easy to combine with Github and offers extension for Chrome to Github-Zenhub
  - Comprehensible UX

**Comment by sanskar-mk2** [comment]
Sure, we can use Zenhub.

**Comment by SarveshDandapati** [comment]
Zenhub is nice.
Email: dsarvesh911@gmail.com
